export const dummyData = [
  {
    Clients: "Qasim",
    id: "2",
    Contacts: "Atif",
    Project: ["LDA", "DHA"],
    Budget: "400 PKR",
    TOC: "10:00 PM",
    Country: "Pakistan",
    Status: ["SOLD", "RENT", "PENDING"],
    Interest: ["5 Marla", "10 Marla", "20 Marla"],
    Email: "Atif@gmail.com",
    Task: ["SOLD", "RENT", "PENDING"],
    Deadline: "11-28-20",
    Returned: ["SOLD", "RENT", "PENDING"],
  },
  {
    Clients: "Qasim",
    id: "2",
    Contacts: "Atif",
    Project: ["LDA", "DHA"],
    Budget: "400 PKR",
    TOC: "10:00 PM",
    Country: "Pakistan",
    Status: ["SOLD", "RENT", "PENDING"],
    Interest: ["5 Marla", "10 Marla", "20 Marla"],
    Email: "Atif@gmail.com",
    Task: ["SOLD", "RENT", "PENDING"],
    Deadline: "11-28-20",
    Returned: ["SOLD", "RENT", "PENDING"],
  },
  {
    Clients: "Qasim",
    id: "2",
    Contacts: "Atif",
    Project: ["LDA", "DHA"],
    Budget: "400 PKR",
    TOC: "10:00 PM",
    Country: "Pakistan",
    Status: ["SOLD", "RENT", "PENDING"],
    Interest: ["5 Marla", "10 Marla", "20 Marla"],
    Email: "Atif@gmail.com",
    Task: ["SOLD", "RENT", "PENDING"],
    Deadline: "11-28-20",
    Returned: ["SOLD", "RENT", "PENDING"],
  },
  {
    Clients: "Qasim",
    id: "2",
    Contacts: "Atif",
    Project: ["LDA", "DHA"],
    Budget: "400 PKR",
    TOC: "10:00 PM",
    Country: "Pakistan",
    Status: ["SOLD", "RENT", "PENDING"],
    Interest: ["5 Marla", "10 Marla", "20 Marla"],
    Email: "Atif@gmail.com",
    Task: ["SOLD", "RENT", "PENDING"],
    Deadline: "11-28-20",
    Returned: ["SOLD", "RENT", "PENDING"],
  },
  {
    Clients: "Qasim",
    id: "2",
    Contacts: "Atif",
    Project: ["LDA", "DHA"],
    Budget: "400 PKR",
    TOC: "10:00 PM",
    Country: "Pakistan",
    Status: ["SOLD", "RENT", "PENDING"],
    Interest: ["5 Marla", "10 Marla", "20 Marla"],
    Email: "Atif@gmail.com",
    Task: ["SOLD", "RENT", "PENDING"],
    Deadline: "11-28-20",
    Returned: ["SOLD", "RENT", "PENDING"],
  },
  {
    Clients: "Qasim",
    id: "2",
    Contacts: "Atif",
    Project: ["LDA", "DHA"],
    Budget: "400 PKR",
    TOC: "10:00 PM",
    Country: "Pakistan",
    Status: ["SOLD", "RENT", "PENDING"],
    Interest: ["5 Marla", "10 Marla", "20 Marla"],
    Email: "Atif@gmail.com",
    Task: ["SOLD", "RENT", "PENDING"],
    Deadline: "11-28-20",
    Returned: ["SOLD", "RENT", "PENDING"],
  },
  {
    Clients: "Asif",
    id: "6",
    Contacts: "Atif",
    Project: ["LDA", "DHA"],
    Budget: "400 PKR",
    TOC: "10:00 PM",
    Country: "Pakistan",
    Status: ["SOLD", "RENT", "PENDING"],
    Interest: ["5 Marla", "10 Marla", "20 Marla"],
    Email: "Atif@gmail.com",
    Task: ["SOLD", "RENT", "PENDING"],
    Deadline: "11-28-20",
    Returned: ["SOLD", "RENT", "PENDING"],
  },
  {
    Clients: "Hamza",
    id: "7",
    Contacts: "Atif",
    Project: ["LDA", "DHA"],
    Budget: "400 PKR",
    TOC: "10:00 PM",
    Country: "Pakistan",
    Status: ["SOLD", "RENT", "PENDING"],
    Interest: ["5 Marla", "10 Marla", "20 Marla"],
    Email: "Atif@gmail.com",
    Task: ["SOLD", "RENT", "PENDING"],
    Deadline: "11-28-20",
    Returned: ["SOLD", "RENT", "PENDING"],
  },
]

// ];
